name: lucky_dice_version2
description: "This is a Simple Flutter app with some functionality. I have used dart.math to create some random int numbers."

publish_to: "none"

homepage: https://github.com/KASRA10/lucky_dice-version2.git
issue_tracker: https://github.com/KASRA10/lucky_dice-version2.git
documentation: https://github.com/KASRA10/lucky_dice-version2.git
repository: https://github.com/KASRA10/lucky_dice-version2.git

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/images/

  fonts:
    - family: Amaranth
      fonts:
        - asset: lib/fonts/Amaranth.ttf
          style: normal
